models:
  xgboost:
    params:
      n_estimators: 100
      learning_rate: 0.1
      max_depth: 6
      objective: 'reg:squarederror'
      random_state: 42  
  lightgbm:
    params:
      num_leaves: 31
      n_estimators: 100
      learning_rate: 0.05
      objective: 'regression'
      random_state: 42
  prophet:
    enabled: False
    params:
      seasonality_mode: 'multiplicative'
      seasonality_prior_scale: 10.0
      changepoint_prior_scale: 0.05
      yearly_seasonality: True
      weekly_seasonality: True
      daily_seasonality: False

#Feature Engineering
features:
  date_features:
    - day
    - week
    - month
    - quarter
    - year
    - dayofweek
    - dayofyear
    - is_weekend
  
  lag_features:
    - 1
    - 2
    - 3
    - 7
    - 14
    - 21
    - 30
  rolling_features:
    windows: [3,6,14,21,30]
    functions: ['mean','std','min','max','median']
  
#Data Validation
Validation:
  required_columns:
    - 'date'
    - 'sales'
    - 'store_id'
    - 'product_id'
  data_types:
    date: 'datetime64[ns]'
    sales: 'float64'
    store_id: 'int64'
    product_id: 'int64'
  
  value_ranges:
    sales:
      min: 0
      max: 1000000

#Training Configuration
training:
  test_size: 0.2
  validation_size: 0.1
  random_state: 42
  cv_folds: 5
  metrics: 
    - 'rmse'
    - 'mae'
    - 'mape'
    - 'r2'

#Infenrence Configuration
infenrence:
  batch_size: 1000
  prediction_horizon: 30
  confidence_interval: [0.8,0.95]

#Monitoring Configuration
monitoring:
  drift_detection:
    enabled: true
    method: 'kolmogorov-smirnov'
    threshold: 0.1
  performance_monitoring:
    enabled: true
    alert_thresholds:
      rmse: 1000
      mae: 500
      mape: 0.2
      r2: 0.8

